@ECHO OFF

SET /P ORIGINAL=Original "smw_src\src" dir: 
SET /P MODIFIED=Modified "smw_src\src" dir: 
SET /P PATCH=Patch name: 

CALL :MAKE_PATCH_FILES
CALL :DELETE_EMPTY_PATCH
CALL :EXPORT_PATCH_BAT

GOTO EXIT

:EXIT
PAUSE
GOTO :EOF

:MAKE_PATCH_FILES
MKDIR %PATCH%
CALL :CREATE_PATCH bank_0
CALL :CREATE_PATCH bank_1
CALL :CREATE_PATCH bank_2
CALL :CREATE_PATCH bank_3
CALL :CREATE_PATCH bank_4
CALL :CREATE_PATCH bank_5
CALL :CREATE_PATCH bank_6
CALL :CREATE_PATCH bank_7
CALL :CREATE_PATCH bank_C
CALL :CREATE_PATCH bank_D
CALL :CREATE_PATCH header
CALL :CREATE_PATCH macros
CALL :CREATE_PATCH main
EXIT /B 0

:CREATE_PATCH
..\bin\diff %ORIGINAL%\%1.asm %MODIFIED%\%1.asm > %PATCH%\%1.diff
EXIT /B 0

:DELETE_EMPTY_PATCH
CALL :DELETE_IF_EMPTY %PATCH%\bank_0.diff
CALL :DELETE_IF_EMPTY %PATCH%\bank_1.diff
CALL :DELETE_IF_EMPTY %PATCH%\bank_2.diff
CALL :DELETE_IF_EMPTY %PATCH%\bank_3.diff
CALL :DELETE_IF_EMPTY %PATCH%\bank_4.diff
CALL :DELETE_IF_EMPTY %PATCH%\bank_5.diff
CALL :DELETE_IF_EMPTY %PATCH%\bank_6.diff
CALL :DELETE_IF_EMPTY %PATCH%\bank_7.diff
CALL :DELETE_IF_EMPTY %PATCH%\bank_C.diff
CALL :DELETE_IF_EMPTY %PATCH%\bank_D.diff
CALL :DELETE_IF_EMPTY %PATCH%\header.diff
CALL :DELETE_IF_EMPTY %PATCH%\macros.diff
CALL :DELETE_IF_EMPTY %PATCH%\main.diff
EXIT /B 0

:DELETE_IF_EMPTY
IF %~z1 EQU 0 DEL %1
EXIT /B 0

:EXPORT_PATCH_BAT
ECHO @ECHO OFF> %PATCH%\patch.bat
ECHO.>> %PATCH%\patch.bat
CALL :EXPORT_IF_EXIST bank_0
CALL :EXPORT_IF_EXIST bank_1
CALL :EXPORT_IF_EXIST bank_2
CALL :EXPORT_IF_EXIST bank_3
CALL :EXPORT_IF_EXIST bank_4
CALL :EXPORT_IF_EXIST bank_5
CALL :EXPORT_IF_EXIST bank_6
CALL :EXPORT_IF_EXIST bank_7
CALL :EXPORT_IF_EXIST bank_C
CALL :EXPORT_IF_EXIST bank_D
CALL :EXPORT_IF_EXIST header
CALL :EXPORT_IF_EXIST macros
CALL :EXPORT_IF_EXIST main
ECHO.>> %PATCH%\patch.bat
ECHO GOTO EXIT>> %PATCH%\patch.bat
ECHO.>> %PATCH%\patch.bat
ECHO :EXIT>> %PATCH%\patch.bat
ECHO @PAUSE>> %PATCH%\patch.bat
ECHO EXIT>> %PATCH%\patch.bat
EXIT /B 0

:EXPORT_IF_EXIST
IF EXIST %PATCH%\%1.diff ECHO ..\..\bin\patch ..\..\src\%1.asm %1.diff>> %PATCH%\patch.bat
EXIT /B 0
