if "%1" == "/c" goto COMPRESS_GRAPHICS
if "%1" == "/d" goto DECOMPRESS_GRAPHICS
echo Invalid arguments.
echo /c to compress
echo /d to decrompress
exit /b

:DECOMPRESS_GRAPHICS
SET program=decomp
GOTO GRAPHICS_ROUTINE

:COMPRESS_GRAPHICS
SET program=recomp
GOTO GRAPHICS_ROUTINE

:GR_FILE
%program% graphics\%1.bin graphics\%1.tmp 0 1 0
exit /b 0

:GRAPHICS_ROUTINE
echo Hold enter for a couple seconds until all graphics are finished!!
echo.
pause
CALL :GR_FILE GFX00
CALL :GR_FILE GFX01
CALL :GR_FILE GFX02
CALL :GR_FILE GFX03
CALL :GR_FILE GFX04
CALL :GR_FILE GFX05
CALL :GR_FILE GFX06
CALL :GR_FILE GFX07
CALL :GR_FILE GFX08
CALL :GR_FILE GFX09
CALL :GR_FILE GFX0A
CALL :GR_FILE GFX0B
CALL :GR_FILE GFX0C
CALL :GR_FILE GFX0D
CALL :GR_FILE GFX0E
CALL :GR_FILE GFX0F
CALL :GR_FILE GFX10
CALL :GR_FILE GFX11
CALL :GR_FILE GFX12
CALL :GR_FILE GFX13
CALL :GR_FILE GFX14
CALL :GR_FILE GFX15
CALL :GR_FILE GFX16
CALL :GR_FILE GFX17
CALL :GR_FILE GFX18
CALL :GR_FILE GFX19
CALL :GR_FILE GFX1A
CALL :GR_FILE GFX1B
CALL :GR_FILE GFX1C
CALL :GR_FILE GFX1D
CALL :GR_FILE GFX1E
CALL :GR_FILE GFX1F
CALL :GR_FILE GFX20
CALL :GR_FILE GFX21
CALL :GR_FILE GFX22
CALL :GR_FILE GFX23
CALL :GR_FILE GFX24
CALL :GR_FILE GFX25
CALL :GR_FILE GFX26
CALL :GR_FILE GFX28
CALL :GR_FILE GFX29
CALL :GR_FILE GFX2A
CALL :GR_FILE GFX2B
CALL :GR_FILE GFX2C
CALL :GR_FILE GFX2D
CALL :GR_FILE GFX2E
CALL :GR_FILE GFX2F
CALL :GR_FILE GFX30
CALL :GR_FILE GFX31
CALL :GR_FILE GFX32
CALL :GR_FILE GFX33

IF %program% == recomp GOTO PGFX27
IF %program% == decomp GOTO LGFX27

:PGFX27
bpp++ 3P 3L graphics\GFX27.bin graphics\GFX27.xyz
MOVE /Y graphics\GFX27.xyz graphics\GFX27.bin
CALL :GR_FILE GFX27
GOTO FINISHGR

:LGFX27
CALL :GR_FILE GFX27
bpp++ 3L 3P graphics\GFX27.tmp graphics\GFX27.xyz
MOVE /Y graphics\GFX27.xyz graphics\GFX27.tmp
GOTO FINISHGR

:FINISHGR
cd graphics
del GFX*.bin
ren GFX*.tmp GFX*.bin
cd ..
echo.
echo All done!
exit /b
